spring:
  config:
    import: aws-secretsmanager:hgjo-1-secretmanager
  datasource:
    url: ${db.url}
    username: ${db.user}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${db.password}
